¶Ifinal_url°DtypeLhttp_headers¢DtypeEvalueä¢Ak¢DtypeEvalueSContent-DispositionAv¢DtypeEvalueX(attachment; filename=example_results.zip¢Ak¢DtypeEvalueQTransfer-EncodingAv¢DtypeEvalueGchunked¢Ak¢DtypeEvalueJSet-CookieAv¢DtypeEvalueY5session=.eJy9zrkOgkAUheFXMVNbOHcowIRGEyFmmIJEhmtjZsEFlxAZkSW8u9hb25zi5C--gbzq4nmwyqm6cGQ5EArfnWmyJBzOjZa7xsDGoUwdZyuK97ZCGpQq35bTV2mgFbKkQbh1CJurkoFTUvSciQXmaYVdQE3UNlPbc8g8lPSto-xo7llvZbsw1G-TS9Dtc0F1PDWPtLenMCTjnID3b0on1r8p_r8lHmfbm2FZbePkZWMBZBzHD3mLjQo.Dz3XKA.ZjTF1NSGrwbfWLWQK7pQHsAHxlA; HttpOnly; Path=/¢Ak¢DtypeEvalueGExpiresAv¢DtypeEvalueXFri, 08 Feb 2019 02:50:16 GMT¢Ak¢DtypeEvalueJKeep-AliveAv¢DtypeEvalueRtimeout=5, max=100¢Ak¢DtypeEvalueFServerAv¢DtypeEvalueXWerkzeug/0.14.1 Python/2.7.14¢Ak¢DtypeEvalueJConnectionAv¢DtypeEvalueJKeep-Alive¢Ak¢DtypeEvalueMCache-ControlAv¢DtypeEvalueUpublic, max-age=43200¢Ak¢DtypeEvalueDDateAv¢DtypeEvalueXThu, 07 Feb 2019 14:50:16 GMT¢Ak¢DtypeEvalueLContent-TypeAv¢DtypeEvalueOapplication/zipMis_redirected¢DtypeEvalueÙLerror_reason¢DtypeEvalueSMime does not matchIhttp_code¢DtypeEvalue»Qdownload_complete¢DtypeEvalueı